package com.example.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.BackendApi
import com.example.model.*
import com.example.ui.theme.*

@Composable
fun SchoolsTabContent(schools: SchoolDirectorySeed, userRole: UserRole, onUploadExcelClick: () -> Unit) {
  var records by remember { mutableStateOf<List<SchoolRecord>>(emptyList()) }
  var search by remember { mutableStateOf("") }; var filter by remember { mutableStateOf("all") }; var loading by remember { mutableStateOf(true) }; var error by remember { mutableStateOf<String?>(null) }; var editing by remember { mutableStateOf<SchoolRecord?>(null) }; var deleting by remember { mutableStateOf<SchoolRecord?>(null) }; var busy by remember { mutableStateOf<String?>(null) }; var add by remember { mutableStateOf(false) }
  val canAdd = userRole == UserRole.Admin || userRole == UserRole.Cluster_Head
  val canManage = userRole == UserRole.Admin
  fun reload() { loading = true; error = null; BackendApi.getSchools({ records = it; loading = false }, { error = it; loading = false }) }
  LaunchedEffect(userRole) { reload() }
  val filtered = records.filter { s -> (filter == "all" || if (filter == "active") s.isActive else !s.isActive) && (search.isBlank() || listOf(s.schoolName, s.udiseCode, s.clusterName, s.clusterCode, s.hmName).any { it.contains(search.trim(), true) }) }
  if (add) { SchoolRegistrationScreen(BackendApi.currentSession(), { add = false }, { add = false; reload() }); return }
  LazyColumn(Modifier.fillMaxSize().padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(11.dp), contentPadding = PaddingValues(bottom = 20.dp)) {
    item { Row(Modifier.fillMaxWidth().padding(top = 7.dp), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text("शाळा व्यवस्थापन", fontSize = 22.sp, fontWeight = FontWeight.Black, color = Color(0xFF172033)); Text(scopeText(userRole), fontSize = 11.sp, color = Color(0xFF64748B)) }; Surface(color = Color(0xFFEDE7F6), shape = RoundedCornerShape(14.dp)) { Column(Modifier.padding(horizontal = 14.dp, vertical = 6.dp), horizontalAlignment = Alignment.CenterHorizontally) { Text(records.size.toString(), fontSize = 21.sp, fontWeight = FontWeight.Black, color = HighDensityPrimary); Text("एकूण शाळा", fontSize = 9.sp, color = HighDensityPrimary) } }; IconButton({ reload() }) { Icon(Icons.Default.Refresh, "Refresh", tint = HighDensityPrimary) } } }
    if (canAdd) item { Surface(onClick = { add = true }, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), color = Color(0xFFF5F1FF), border = androidx.compose.foundation.BorderStroke(1.dp, Color(0xFFE2D7FF))) { Row(Modifier.padding(15.dp), verticalAlignment = Alignment.CenterVertically) { Surface(color = HighDensityPrimary, shape = RoundedCornerShape(12.dp)) { Icon(Icons.Default.AddBusiness, null, tint = Color.White, modifier = Modifier.padding(11.dp).size(25.dp)) }; Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f)) { Text("नवीन शाळा नोंदणी", fontSize = 15.sp, fontWeight = FontWeight.Black, color = Color(0xFF35166F)); Text(if (userRole == UserRole.Cluster_Head) "आपल्या केंद्रातील नवीन शाळा नोंदवा." else "UDISE, केंद्र व शाळेची माहिती सुरक्षितपणे जतन करा.", fontSize = 11.sp, color = Color(0xFF5B4B78)) }; Icon(Icons.Default.ChevronRight, null, tint = HighDensityPrimary) } } }
    item { Surface(Modifier.fillMaxWidth(), RoundedCornerShape(16.dp), color = Color.White) { Column(Modifier.padding(12.dp)) { Text("शाळा शोधा", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = Color(0xFF475569)); Spacer(Modifier.height(6.dp)); OutlinedTextField(search, { search = it }, Modifier.fillMaxWidth(), singleLine = true, shape = RoundedCornerShape(14.dp), placeholder = { Text("शाळेचे नाव, UDISE किंवा केंद्र शोधा…") }, leadingIcon = { Icon(Icons.Default.Search, null) }, trailingIcon = { if (search.isNotEmpty()) IconButton({ search = "" }) { Icon(Icons.Default.Clear, "Clear") } }) } } }
    item { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(7.dp)) { FilterChip(filter == "all", { filter = "all" }, label = { Text("सर्व ${records.size}", fontSize = 9.sp) }); FilterChip(filter == "active", { filter = "active" }, label = { Text("सक्रिय ${records.count { it.isActive }}", fontSize = 9.sp) }); FilterChip(filter == "inactive", { filter = "inactive" }, label = { Text("निष्क्रिय ${records.count { !it.isActive }}", fontSize = 9.sp) }) } }
    item { Text("${filtered.size} नोंदणीकृत शाळा", fontSize = 16.sp, fontWeight = FontWeight.Black, color = Color(0xFF172033)) }
    if (loading) item { Box(Modifier.fillMaxWidth().padding(28.dp), contentAlignment = Alignment.Center) { CircularProgressIndicator() } } else if (error != null) item { Text(error.orEmpty(), color = Color(0xFFC62828), fontSize = 11.sp) } else if (filtered.isEmpty()) item { Surface(Modifier.fillMaxWidth(), RoundedCornerShape(18.dp), color = Color.White) { Column(Modifier.padding(28.dp), horizontalAlignment = Alignment.CenterHorizontally) { Icon(Icons.Default.School, null, tint = Color(0xFF94A3B8), modifier = Modifier.size(40.dp)); Text("शाळा सापडली नाही", fontWeight = FontWeight.Bold) } } } else items(filtered, key = { it.id }) { school -> SchoolCard(school, canManage, busy == school.id, { editing = school }, { busy = school.id; BackendApi.setSchoolActive(school.id, !school.isActive, { busy = null; reload() }, { busy = null; error = it }) }, { deleting = school }) }
  }
  editing?.let { SchoolEditDialog(it, { editing = null; reload() }, { editing = null }) }
  deleting?.let { school -> AlertDialog(onDismissRequest = { deleting = null }, title = { Text("शाळा हटवायची आहे?") }, text = { Text("‘${school.schoolName}’ ही नोंद हटवली जाईल. संबंधित वापरकर्ते असल्यास delete नाकारले जाईल.") }, confirmButton = { TextButton({ deleting = null; busy = school.id; BackendApi.deleteSchool(school.id, { busy = null; reload() }, { busy = null; error = it }) }) { Text("हटवा", color = Color(0xFFC62828)) } }, dismissButton = { TextButton({ deleting = null }) { Text("रद्द करा") } }) }
}

@Composable private fun SchoolCard(s: SchoolRecord, canManage: Boolean, busy: Boolean, edit: () -> Unit, toggle: () -> Unit, delete: () -> Unit) { Surface(Modifier.fillMaxWidth(), RoundedCornerShape(18.dp), color = Color.White, tonalElevation = 1.dp) { Column(Modifier.padding(14.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Icon(Icons.Default.School, null, tint = HighDensityPrimary, modifier = Modifier.size(24.dp)); Spacer(Modifier.width(9.dp)); Column(Modifier.weight(1f)) { Text(s.schoolName, fontSize = 15.sp, fontWeight = FontWeight.Black, maxLines = 2, overflow = TextOverflow.Ellipsis); Text(if (s.isActive) "सक्रिय" else "निष्क्रिय", fontSize = 10.sp, fontWeight = FontWeight.Bold, color = if (s.isActive) Color(0xFF137333) else Color(0xFFC62828)) } }; Spacer(Modifier.height(8.dp)); Text("UDISE: ${s.udiseCode}", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = Color(0xFF475569)); Text("केंद्र: ${s.clusterName} • ${s.clusterCode}", fontSize = 10.sp, color = Color(0xFF475569), modifier = Modifier.padding(top = 4.dp)); if (s.hmName.isNotBlank()) Text("मुख्याध्यापक: ${s.hmName} ${s.hmMobile}", fontSize = 10.sp, color = Color(0xFF475569), modifier = Modifier.padding(top = 4.dp)); if (canManage) { HorizontalDivider(Modifier.padding(top = 7.dp)); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) { IconButton(onClick = { edit() }, enabled = !busy) { Icon(Icons.Default.Edit, "Edit", tint = Color(0xFF5E35B1)) }; IconButton(onClick = { toggle() }, enabled = !busy) { Icon(if (s.isActive) Icons.Default.ToggleOn else Icons.Default.ToggleOff, "Status", tint = if (s.isActive) Color(0xFFC62828) else Color(0xFF2E7D32)) }; IconButton(onClick = { delete() }, enabled = !busy) { Icon(Icons.Default.DeleteOutline, "Delete", tint = Color(0xFFC62828)) } } } } } }

@Composable private fun SchoolEditDialog(s: SchoolRecord, onSaved: () -> Unit, onClose: () -> Unit) { var name by remember(s.id) { mutableStateOf(s.schoolName) }; var cn by remember(s.id) { mutableStateOf(s.clusterName) }; var cc by remember(s.id) { mutableStateOf(s.clusterCode) }; var taluka by remember(s.id) { mutableStateOf(s.taluka) }; var district by remember(s.id) { mutableStateOf(s.district) }; var hm by remember(s.id) { mutableStateOf(s.hmName) }; var mobile by remember(s.id) { mutableStateOf(s.hmMobile) }; var type by remember(s.id) { mutableStateOf(s.schoolType) }; var active by remember(s.id) { mutableStateOf(s.isActive) }; var saving by remember { mutableStateOf(false) }; var error by remember { mutableStateOf<String?>(null) }; AlertDialog(onDismissRequest = onClose, title = { Text("शाळा माहिती संपादित करा") }, text = { Column(verticalArrangement = Arrangement.spacedBy(6.dp)) { OutlinedTextField(name, { name = it }, label = { Text("शाळेचे नाव") }, singleLine = true); OutlinedTextField(s.udiseCode, {}, label = { Text("UDISE कोड") }, enabled = false, singleLine = true); OutlinedTextField(cn, { cn = it }, label = { Text("केंद्र") }, singleLine = true); OutlinedTextField(cc, { cc = it }, label = { Text("केंद्र कोड") }, singleLine = true); OutlinedTextField(taluka, { taluka = it }, label = { Text("तालुका") }, singleLine = true); OutlinedTextField(district, { district = it }, label = { Text("जिल्हा") }, singleLine = true); OutlinedTextField(hm, { hm = it }, label = { Text("मुख्याध्यापक") }, singleLine = true); OutlinedTextField(mobile, { mobile = it }, label = { Text("मोबाईल") }, singleLine = true); OutlinedTextField(type, { type = it }, label = { Text("शाळेचा प्रकार") }, singleLine = true); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text(if (active) "सक्रिय" else "निष्क्रिय"); Switch(active, { active = it }) }; error?.let { Text(it, color = Color(0xFFC62828), fontSize = 10.sp) } } }, confirmButton = { TextButton(enabled = !saving, onClick = { saving = true; BackendApi.updateSchool(s.id, name.trim(), cn.trim(), cc.trim(), taluka.trim(), district.trim(), hm.trim(), mobile.trim(), type.trim(), active, { saving = false; onSaved() }, { saving = false; error = it }) }) { Text(if (saving) "जतन…" else "जतन करा") } }, dismissButton = { TextButton(onClick = onClose) { Text("रद्द करा") } }) }

private fun scopeText(r: UserRole) = when (r) { UserRole.Admin -> "सर्व केंद्रे व शाळांची माहिती"; UserRole.Cluster_Head -> "आपले केंद्र • संबंधित शाळा"; UserRole.School_HM -> "आपली शाळा • संबंधित माहिती"; UserRole.Teacher -> "आपली शाळा • उपलब्ध माहिती" }
