package com.example.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.AccountBalance
import androidx.compose.material.icons.filled.LocationOn
import androidx.compose.material.icons.filled.Phone
import androidx.compose.material.icons.filled.School
import androidx.compose.material.icons.filled.Tag
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.BackendApi
import com.example.model.UserSession
import com.example.ui.theme.HighDensityBackground

@Composable
fun SchoolRegistrationScreen(
  session: UserSession,
  onBack: () -> Unit,
  onRegistered: (String) -> Unit
) {
  var schoolName by remember { mutableStateOf("") }
  var udiseCode by remember { mutableStateOf("") }
  var clusterName by remember { mutableStateOf("") }
  var clusterCode by remember { mutableStateOf("") }
  var taluka by remember { mutableStateOf("") }
  var district by remember { mutableStateOf("") }
  var hmName by remember { mutableStateOf("") }
  var hmMobile by remember { mutableStateOf("") }
  var schoolType by remember { mutableStateOf("") }
  var isActive by remember { mutableStateOf(true) }
  var errorMessage by remember { mutableStateOf<String?>(null) }
  var submitting by remember { mutableStateOf(false) }

  Scaffold(
    containerColor = HighDensityBackground,
    topBar = {
      TopAppBar(
        title = {
          Column {
            Text("School Registration", fontWeight = FontWeight.Bold)
            Text("Register a school in the D1 schools table", fontSize = 12.sp, color = Color(0xFF64748B))
          }
        },
        navigationIcon = {
          IconButton(onClick = onBack) {
            Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
          }
        }
      )
    }
  ) { paddingValues ->
    Column(
      modifier = Modifier
        .fillMaxSize()
        .padding(paddingValues)
        .verticalScroll(rememberScrollState())
        .navigationBarsPadding()
        .padding(horizontal = 16.dp, vertical = 12.dp),
      verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
      Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = Color(0xFFEDE7F6))
      ) {
        Column(modifier = Modifier.padding(16.dp)) {
          Row(verticalAlignment = Alignment.CenterVertically) {
            Icon(Icons.Default.School, contentDescription = null, tint = Color(0xFF6750A4))
            Text(" SCHOOL MASTER RECORD", fontWeight = FontWeight.Black, fontSize = 14.sp)
          }
          Spacer(modifier = Modifier.height(6.dp))
          Text(
            "Fields follow the canonical schools table. ID and timestamps are generated by the backend; is_active is controlled below.",
            fontSize = 12.sp,
            color = Color(0xFF475569)
          )
        }
      }

      SchoolField("School Name *", schoolName, { schoolName = it }, Icons.Default.School)
      SchoolField("UDISE / School Code *", udiseCode, { udiseCode = it }, Icons.Default.Tag, KeyboardType.Number)
      SchoolField("Cluster Name *", clusterName, { clusterName = it }, Icons.Default.AccountBalance)
      SchoolField("Cluster Code *", clusterCode, { clusterCode = it }, Icons.Default.Tag, KeyboardType.Number)
      SchoolField("Taluka", taluka, { taluka = it }, Icons.Default.LocationOn)
      SchoolField("District", district, { district = it }, Icons.Default.LocationOn)
      SchoolField("HM Name", hmName, { hmName = it }, Icons.Default.AccountBalance)
      SchoolField("HM Mobile", hmMobile, { hmMobile = it }, Icons.Default.Phone, KeyboardType.Phone)
      SchoolField("School Type", schoolType, { schoolType = it }, Icons.Default.School)

      Card(modifier = Modifier.fillMaxWidth()) {
        Row(
          modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 10.dp),
          horizontalArrangement = Arrangement.SpaceBetween,
          verticalAlignment = Alignment.CenterVertically
        ) {
          Column {
            Text("Active School", fontWeight = FontWeight.Bold)
            Text("maps to schools.is_active", fontSize = 12.sp, color = Color(0xFF64748B))
          }
          Switch(checked = isActive, onCheckedChange = { isActive = it })
        }
      }

      errorMessage?.let {
        Text(it, color = Color(0xFFB3261E), fontWeight = FontWeight.SemiBold, fontSize = 13.sp)
      }

      Button(
        modifier = Modifier.fillMaxWidth().height(52.dp),
        enabled = !submitting,
        onClick = {
          errorMessage = when {
            schoolName.isBlank() -> "School Name is required"
            udiseCode.isBlank() -> "UDISE / School Code is required"
            clusterName.isBlank() -> "Cluster Name is required"
            clusterCode.isBlank() -> "Cluster Code is required"
            else -> null
          }
          if (errorMessage != null) return@Button

          submitting = true
          BackendApi.registerSchool(
            token = session.token,
            schoolName = schoolName.trim(),
            udiseCode = udiseCode.trim(),
            clusterName = clusterName.trim(),
            clusterCode = clusterCode.trim(),
            taluka = taluka.trim(),
            district = district.trim(),
            hmName = hmName.trim(),
            hmMobile = hmMobile.trim(),
            schoolType = schoolType.trim(),
            isActive = isActive,
            onSuccess = {
              submitting = false
              onRegistered(it)
            },
            onError = {
              submitting = false
              errorMessage = it
            }
          )
        }
      ) {
        Text(if (submitting) "REGISTERING..." else "REGISTER SCHOOL", fontWeight = FontWeight.Bold)
      }

      Text(
        "Required for the next user-registration test: School Name, UDISE/School Code, Cluster Name and Cluster Code.",
        fontSize = 12.sp,
        color = Color(0xFF64748B),
        modifier = Modifier.padding(bottom = 12.dp)
      )
    }
  }
}

@Composable
private fun SchoolField(
  label: String,
  value: String,
  onValueChange: (String) -> Unit,
  icon: androidx.compose.ui.graphics.vector.ImageVector,
  keyboardType: KeyboardType = KeyboardType.Text
) {
  OutlinedTextField(
    value = value,
    onValueChange = onValueChange,
    label = { Text(label) },
    leadingIcon = { Icon(icon, contentDescription = null) },
    keyboardOptions = KeyboardOptions(keyboardType = keyboardType),
    singleLine = true,
    modifier = Modifier.fillMaxWidth()
  )
}
